### ISSUE TITLE
Terminar triangulito

### ISSUE THREAD

**Issue by rodp63** [mgonnav/CG-3-Mosqueteros#11]
#### Missing:
- [x] Triangles Animation 
- [x] Set keys to control the execution (if necessary)
- [x] Set proper shader colors according to node level

**Comment by mgonnav** [comment]
Triangles Animation done in #12

**Comment by mgonnav** [comment]
Set colors in #13

**Comment by mgonnav** [comment]
Change colors via keyboard #15
